"""Physical-scale-aware DOM tiling.

Tiles are generated by **real-world ground coverage**, not by fixed pixel
windows.  For each scale ``k`` with physical width ``W_k`` and DOM GSD ``g``:

* tile pixel size in DOM = ``W_k / g``
* step size             = ``tile_size * (1 - overlap)``
* each tile is resized to ``network_input_size`` before inference

This means a small rock that occupies only a few pixels at the coarse scale
can occupy hundreds of pixels at the fine scale, giving the network a chance
to detect it.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import rasterio
from PIL import Image
from rasterio.windows import Window

from .config import ScaleConfig
from .models import TileMetadata


def generate_tiles(
    dom_width: int,
    dom_height: int,
    scale: ScaleConfig,
    gsd: float,
    overlap_ratio: float,
) -> list[TileMetadata]:
    """Generate tiles covering the DOM at a given physical scale.

    Parameters
    ----------
    dom_width, dom_height
        DOM pixel dimensions.
    scale
        Scale configuration (includes physical width and network input size).
    gsd
        Ground sampling distance in metres per pixel.
    overlap_ratio
        Fractional overlap between adjacent tiles (0.0 – 0.5).

    Returns
    -------
    list[TileMetadata]
        One entry per tile, with DOM pixel coordinates.
    """
    tile_size = scale.dom_pixel_size(gsd)
    step = max(1, int(tile_size * (1.0 - overlap_ratio)))
    resample_factor = scale.resample_factor(gsd)

    tiles: list[TileMetadata] = []
    counter = 0

    y = 0
    while y < dom_height:
        x = 0
        while x < dom_width:
            tw = min(tile_size, dom_width - x)
            th = min(tile_size, dom_height - y)

            if tw > 0 and th > 0:
                tile_id = f"{scale.level.value}_{counter:06d}"
                tiles.append(TileMetadata(
                    tile_id=tile_id,
                    scale_level=scale.level.value,
                    x_start=x,
                    y_start=y,
                    width=tw,
                    height=th,
                    resample_factor=resample_factor,
                ))
                counter += 1

            x += step
        y += step

    return tiles


class DOMReader:
    """Reader for DOM GeoTIFF files with efficient windowed access.

    Keeps the rasterio dataset handle open for the lifetime of the reader,
    so repeated ``read_tile`` calls do not incur file-open overhead.
    """

    def __init__(self, dom_path: str | Path):
        self.dom_path = str(dom_path)
        self._src = rasterio.open(self.dom_path)
        self.width: int = self._src.width
        self.height: int = self._src.height

    def read_tile(
        self,
        tile: TileMetadata,
        network_input_size: int,
    ) -> np.ndarray:
        """Read a tile region from the DOM and resize to network input.

        Returns
        -------
        np.ndarray
            Image of shape ``(network_input_size, network_input_size, 3)``,
            dtype ``uint8``, suitable for YOLO inference.
        """
        window = Window(
            col_off=tile.x_start,
            row_off=tile.y_start,
            width=tile.width,
            height=tile.height,
        )
        data = self._src.read(window=window)  # (bands, h, w)
        image = np.transpose(data, (1, 2, 0))  # (h, w, bands)

        image = _normalise_to_rgb_uint8(image)

        if tile.width != network_input_size or tile.height != network_input_size:
            pil_img = Image.fromarray(image)
            pil_img = pil_img.resize(
                (network_input_size, network_input_size),
                Image.BILINEAR,
            )
            image = np.array(pil_img)

        return image

    def close(self) -> None:
        if self._src is not None:
            self._src.close()
            self._src = None

    def __enter__(self) -> DOMReader:
        return self

    def __exit__(self, *args: object) -> None:
        self.close()

    def __del__(self) -> None:
        self.close()


def _normalise_to_rgb_uint8(image: np.ndarray) -> np.ndarray:
    """Ensure the image is 3-band RGB uint8.

    Handles single-band grayscale and multi-band inputs.
    """
    if image.ndim == 2:
        image = image[:, :, np.newaxis]

    if image.shape[2] == 1:
        image = np.repeat(image, 3, axis=2)
    elif image.shape[2] >= 3:
        image = image[:, :, :3]

    if image.dtype != np.uint8:
        image = image.astype(np.float32)
        max_val = image.max()
        if max_val > 0:
            image = image / max_val * 255.0
        image = image.astype(np.uint8)

    return image
